platformName: Android
# simulator 模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:62025

#mx4phone 真机
#platformVersion: 5.1
#udid: 750BBKL22GDN
#deviceName: MX4

appname: kaoyan3.1.0.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True
app: F:/Appium/Projects/kyb_testPro/app/kaoyan3.1.0.apk

appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity
ip: 127.0.0.1
port: 4723
